; Minimal LovyanGFX project — Elecrow C3 1.28" (GC9A01 240×240 round, ESP32-C3)
; https://github.com/lovyan03/LovyanGFX

[env:holographic_esp32_display]
extra_scripts = pre:pre_script.py
platform  = espressif32@6.9.0
framework = arduino
board     = esp32-2424S012N
board_dir = boards
board_build.partitions = partitions.csv
monitor_speed = 115200
lib_deps =
    lovyan03/LovyanGFX@1.1.16
    tzapu/WiFiManager
